language: node_js
node_js:
  - lts/*
script:
  - npm run lint
  - npm run test
before_install:
  - (mkdir /tmp/zpaq && cd /tmp/zpaq && wget http://mattmahoney.net/dc/zpaq715.zip && unzip ./zpaq715.zip && make) # uses brackets to not actually leave the cwd
env:
  - zpaq=/tmp/zpaq/zpaq
